### ISSUE TITLE
-

### ISSUE THREAD

**Issue by rzlyp** [nordhagen/instagram-tagscrape#4]
hello

**Comment by evolross** [comment]
I’ll look at it, but not until early next week. On vacation currently.

**Comment by smartium** [comment]
The entire JSON structure has been changed to be compatible with grahql. The dict 'media', would now be in Array: 'graphql.hashtag.edge_hashtag_to_media.edges[n]'.

**Comment by banbara23** [comment]
I am getting the same error.

```
node_modules/instagram-tagscrape/index.js:48
                var media = data.entry_data.TagPage[0].tag.media;
                                                           ^

TypeError: Cannot read property 'media' of undefined
```

**Comment by evolross** [comment]
This is now fixed in my [fork](https://github.com/evolross/instagram-tagscrape). Pull request submitted for this project.

NOTE: It's also fixed in some of the other [forks](https://github.com/nordhagen/instagram-tagscrape/network) of this project.
